### ISSUE TITLE
build direclty

### ISSUE THREAD

**Issue by okanduzyel** [AchimPieters/HomeKit-Core#1]
Hi,

I have installed docker, esp sdk, rtos and esp-homekit-demo files correctly on my Mac. 

According to your installation guide, https://www.studiopieters.nl/esp-homekit-sdk-full-installation/ you extract a .bin file and then, flash it to esp. 

Is there any to build and flash it directly like linux like that command "make -C . test"?

**Comment by AchimPieters** [comment]
make -C examples/led test

**Comment by okanduzyel** [comment]
okanduzyel@MacBook-Pro esp-homekit-demo % make -C examples/led test
Makefile:13: /Users/okanduzyel/ESP/esp/esp-open-rtos/common.mk: No such file or directory
make: *** No rule to make target `/Users/okanduzyel/ESP/esp/esp-open-rtos/common.mk'.  Stop.

**Comment by AchimPieters** [comment]
You probably didn’t do git submodule update --init --recursive

**Comment by okanduzyel** [comment]
I did. I still gives same error.

**Comment by AchimPieters** [comment]
Dus you set the PATH?

**Comment by okanduzyel** [comment]
Yes, I did it according to your building instructions.

**Comment by AchimPieters** [comment]
check your path: `/Users/okanduzyel/ESP/esp/esp-open-rtos/common.mk: No such file or directory`

**Comment by okanduzyel** [comment]
Could you show me how I can path it with codes?

(I guess, I have already done it but I couldn't be sure about that)

**Comment by AchimPieters** [comment]
eg. `export SDK_PATH=~/esp/esp-open-rtos`

**Comment by okanduzyel** [comment]
Yes! the problem is that:

```
okanduzyel@MacBook-Pro led % make -C . test                     
esptool.py -p /dev/cu.wchusbserial1410 --baud 115200 write_flash -fs 32m -fm qio -ff 40m \
		0x0 /Users/okanduzyel/esp/esp-open-rtos/bootloader/firmware_prebuilt/rboot.bin 0x1000 /Users/okanduzyel/esp/esp-open-rtos/bootloader/firmware_prebuilt/blank_config.bin 0x2000 ./firmware/led.bin 

```

It tries to find led.bin file. Before `make -C command`, we should extract bin. file into firmware folder with that code:

`docker run -it --rm -v `pwd`:/project -w /project esp-rtos make -C examples/led all`

This is exactly working. Thank you so much @AchimPieters
